# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: xenial

matrix:
  include:
   - os: linux
     r: release
   - os: linux
     r: devel

cache:
  packages: TRUE


